---
default_stages:
  - pre-commit
fail_fast: false
minimum_pre_commit_version: 2.15.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # v6.0.0
    hooks:
      # Git hooks
      - id: check-added-large-files
        args:
          - --maxkb=2000
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-submodules
      - id: no-commit-to-branch
        args:
          - --branch
          - main

      # Common errors
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md,markdown,mdown,mkd"

      # JSON
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
          - --no-ensure-ascii
          - --no-sort-keys

      # Cross platform
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: destroyed-symlinks
      - id: mixed-line-ending
        args:
          - --fix=lf

      # Security
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.1 # v0.48.0
    hooks:
      - id: markdownlint
        args:
          - --fix

  # Shell
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1 # v0.11.0.1
    hooks:
      - id: shellcheck
        args:
          - --severity=warning

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.1-1 # v3.13.1-1
    hooks:
      - id: shfmt
        args:
          - -i
          - "2"
          - -ci
          - -bn

  # Gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0 # v8.30.0
    hooks:
      - id: gitleaks

  # YAML
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0 # v0.20.0
    hooks:
      - id: yamlfmt
        exclude: ^\.pre-commit-config\.yaml$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0 # v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c=.yamllint.yml

  - repo: local
    hooks:
      - id: sync
        name: sync marketplace index
        language: script
        entry: scripts/sync.sh
        pass_filenames: false
        always_run: true
